<?xml version="1.0" encoding="utf-8"?><Database Name="14-602" Class="ProductDataDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\sqlexpress;Initial Catalog=14-602;Integrated Security=True" SettingsObjectName="_14_602.Properties.Settings" SettingsPropertyName="_14_602ConnectionString2" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ProductData" Member="ProductData">
    <Type Name="ProductData">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BarcodeNo" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Date" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Time" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MaxValue" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Function Name="dbo.DeletTable" Method="DeletTable">
    <Return Type="System.Int32" />
  </Function>
</Database>